import {describe,it,expect} from 'vitest';
import fs from 'node:fs';import crypto from 'node:crypto';
import {courses,projects,lessons,documents,checkLesson,checkProject,complete,metrics,fresh,validate,bookmark,milestone,rank,offlineAnswer,day} from '../src/core';
describe('original curriculum and projects',()=>{
 it('includes all courses, lessons, projects and unique identities',()=>{expect(courses).toHaveLength(40);expect(lessons).toHaveLength(400);expect(courses.flatMap(c=>c.modules)).toHaveLength(80);expect(projects).toHaveLength(40);expect(projects.flatMap(p=>p.starterFiles)).toHaveLength(80);expect(projects.flatMap(p=>p.milestones)).toHaveLength(160);expect(documents).toHaveLength(440);expect(new Set(documents.map(d=>d.id)).size).toBe(440);expect(Object.fromEntries(['concept','quiz','code','architecture'].map(k=>[k,lessons.filter(l=>l.lesson.kind===k).length]))).toEqual({concept:80,quiz:100,code:140,architecture:80});});
 it('preserves exact macOS curriculum bytes and original source checksums',()=>{expect(fs.readFileSync('content/curriculum.json').equals(fs.readFileSync('../Ai_Engineering/Resources/curriculum.json'))).toBe(true);for(const p of JSON.parse(fs.readFileSync('content/provenance.json','utf8')))expect(crypto.createHash('sha256').update(fs.readFileSync('../'+p.file)).digest('hex')).toBe(p.sha256);});
 for(const {lesson:l} of lessons)it('validates supplied learning path: '+l.id,()=>{expect(l.contentBlocks.length).toBeGreaterThan(0);const c=l.challenge;if(c?.correctChoiceID){expect(c.choices?.some(x=>x.id===c.correctChoiceID)).toBe(true);expect(checkLesson(l,'wrong').pass).toBe(false);expect(checkLesson(l,c.correctChoiceID).pass).toBe(true);}else if(c?.starterCode!==undefined){expect(checkLesson(l,c.starterCode).pass).toBe(false);if(c.solution)expect(checkLesson(l,c.solution).pass).toBe(true);}else{expect(checkLesson(l,'A reasoned explanation of the concept.').pass).toBe(true);}});
 it('checks all 80 export filenames for Windows compatibility',()=>{for(const p of projects)for(const f of p.starterFiles){expect(f.name).toMatch(/^[-a-zA-Z0-9_. ]+$/);expect(f.name).not.toMatch(/^\.|[. ]$|^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i);expect(f.contents).not.toBe('');}});
});
describe('progress and saved work',()=>{
 it('awards lesson XP only once and preserves recent order',()=>{const s=fresh(),l=lessons[0].lesson;expect(complete(s,l.id,new Date(2026,8,20,23))).toBe(l.xp);expect(complete(s,l.id,new Date(2026,8,21))).toBe(0);expect(metrics(s).xp).toBe(l.xp);expect(s.completed[l.id]).toBe('2026-09-20');expect(s.recent).toEqual([l.id]);});
 it('tracks current streak with local calendar days and resets after a gap',()=>{const s=fresh();complete(s,lessons[0].lesson.id,new Date(2026,8,20,23,59));complete(s,lessons[1].lesson.id,new Date(2026,8,21,0,1));expect(metrics(s,new Date(2026,8,22)).streak).toBe(2);expect(metrics(s,new Date(2026,8,23)).streak).toBe(0);expect(day(new Date(2026,8,21,0,1))).toBe('2026-09-21');});
 it('scopes repeated milestone names to their own project',()=>{const s=fresh(),p=projects[0],m=p.milestones[0];milestone(s,p.id+'::'+m.id);expect(s.milestones).toEqual([p.id+'::'+m.id]);expect(metrics(s).xp).toBe(0);milestone(s,p.id+'::'+m.id);expect(s.milestones).toEqual([]);});
 it('roundtrips work without credentials, and recalculates XP rather than trusting supplied totals',()=>{const s=fresh();complete(s,lessons[0].lesson.id);bookmark(s,courses[0].id);s.drafts[lessons[0].lesson.id]='Grüße 日本語 <script>never execute</script>';s.messages=[offlineAnswer('What is RAG?','',s)];const restored=validate({...JSON.parse(JSON.stringify(s)),totalXP:999999,token:'do-not-copy'});expect(restored).toEqual(s);expect(JSON.stringify(restored)).not.toContain('do-not-copy');expect(metrics(restored).xp).toBe(15);});
 it('limits recent lessons without losing completion history',()=>{const s=fresh();lessons.slice(0,20).forEach(l=>complete(s,l.lesson.id));expect(s.recent).toHaveLength(12);expect(Object.keys(s.completed)).toHaveLength(20);});
 for(const patch of [{version:2},{dailyGoal:0},{dailyGoal:501},{dailyGoal:NaN},{completed:{unknown:'2026-09-01'}},{completed:{[lessons[0].lesson.id]:'2026-02-30'}},{drafts:{unknown:'x'}},{drafts:{[lessons[0].lesson.id]:'x'.repeat(100001)}},{milestones:['read']},{bookmarks:['unknown']},{theme:'evil'},{messages:[{role:'assistant',text:'x',engine:'x',sources:[]}]}])it('rejects invalid backup '+Object.keys(patch).join(','),()=>expect(()=>validate({...fresh(),...patch})).toThrow());
 it('starts with real zero skill XP',()=>expect(metrics(fresh()).skills).toEqual({}));
 it('does not claim to execute project code',()=>{const result=checkProject('a'.repeat(90),'starter');expect(result.pass).toBe(true);expect(result.message).toContain('no code was executed');expect(checkProject('TODO'+'a'.repeat(90),'starter').pass).toBe(false);expect(checkProject('starter','starter').pass).toBe(false);});
});
describe('offline tutoring',()=>{
 it('retrieves curriculum sources and explicitly describes its limits',()=>{const answer=offlineAnswer('Why does RAG need embeddings?','',fresh());expect(answer.sources.length).toBeGreaterThan(0);expect(answer.text).toMatch(/retrieval|embedding/i);expect(answer.text).toContain('does not run a generative model');});
 it('uses lesson context while retaining traceable sources',()=>{expect(rank('Explain this',lessons[0].lesson.id)[0].id).toBe(lessons[0].lesson.id);});
 it('avoids inventing a match for unknown terms',()=>{expect(offlineAnswer('zqxvzzzz','',fresh()).sources).toEqual([]);});
 it('adapts depth and learner level',()=>{const deep=offlineAnswer('gradient descent','',fresh()),focused=offlineAnswer('gradient descent','',{level:'engineer',depth:'focused'});expect(deep.text.length).toBeGreaterThan(focused.text.length);expect(focused.text).toContain('assumptions');});
});
