import {it,expect,describe} from 'vitest';import {createRequire} from 'node:module';import http from 'node:http';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
const require=createRequire(import.meta.url),p=require('../electron/provider.cjs'),{Vault}=require('../electron/vault.cjs');
const payload={system:'Patient teacher',user:'Explain vectors 日本語',deep:true};
describe('provider permissions and data handling',()=>{
 for(const endpoint of ['http://example.com/v1','file:///secrets','https://user:pass@example.com','https://example.com/?key=secret','https://example.com/#token'])it('rejects unsafe endpoint '+endpoint,()=>expect(()=>p.endpoint(endpoint)).toThrow());
 it('pins every named provider to its own endpoint',()=>{for(const id of Object.keys(p.PRESETS).filter(id=>id!=='custom'))expect(()=>p.validateConfig({provider:id,endpoint:'https://evil.example/v1',model:'example'})).toThrow();});
 it('keeps API keys in headers and supports all three protocols',()=>{for(const id of ['openAI','anthropic','googleGemini','ollama']){const c={provider:id,endpoint:p.PRESETS[id][1],model:'example-model'},r=p.makeRequest(c,'synthetic-test-key',payload);expect(r.url+r.body).not.toContain('synthetic-test-key');expect(Object.values(r.headers)).toContain(id==='openAI'||id==='ollama'?'Bearer synthetic-test-key':'synthetic-test-key');expect(JSON.parse(r.body)).toBeTruthy();}});
 it('uses OpenAI completion-token parameter and developer instructions',()=>{const r=p.makeRequest({provider:'openAI',endpoint:p.PRESETS.openAI[1],model:'example'},'test',payload),body=JSON.parse(r.body);expect(body.max_completion_tokens).toBe(1800);expect(body.max_tokens).toBeUndefined();expect(body.messages[0].role).toBe('developer');});
 it('decodes provider-specific text without accepting empty or oversized content',()=>{expect(p.decode({choices:[{message:{content:' Hello '}}]},'compatible')).toBe('Hello');expect(p.decode({content:[{type:'text',text:'Hello'}]},'anthropic')).toBe('Hello');expect(p.decode({candidates:[{content:{parts:[{text:'Hello'}]}}]},'gemini')).toBe('Hello');expect(()=>p.decode({},'gemini')).toThrow();expect(()=>p.decode({choices:[{message:{content:'x'.repeat(30001)}}]},'compatible')).toThrow();});
 it('does not permit hosted credentials over plain HTTP',()=>expect(()=>p.validateConfig({provider:'custom',endpoint:'http://localhost:8000/v1',model:'test'})).toThrow());
});
async function server(handler:http.RequestListener){const s=http.createServer(handler);await new Promise<void>(resolve=>s.listen(0,'127.0.0.1',resolve));const address=s.address() as {port:number};return {url:'http://127.0.0.1:'+address.port,close:()=>new Promise<void>(resolve=>{s.closeAllConnections();s.close(()=>resolve());})};}
it('performs bounded real local HTTP and refuses credential-carrying redirects',async()=>{let redirects=0;const s=await server((req,res)=>{if(req.url==='/redirect'){res.writeHead(302,{Location:'/secret'});res.end();}else if(req.url==='/secret'){redirects++;res.end('{}');}else if(req.url==='/large'){res.end('x'.repeat(101));}else res.end(JSON.stringify({unicode:'Grüße 日本語',authorization:req.headers.authorization}));});try{expect(await p.requestJSON(s.url,{headers:{Authorization:'Bearer synthetic'}})).toEqual({unicode:'Grüße 日本語',authorization:'Bearer synthetic'});await expect(p.requestJSON(s.url+'/redirect',{headers:{Authorization:'Bearer synthetic'}})).rejects.toThrow('302');expect(redirects).toBe(0);await expect(p.requestJSON(s.url+'/large',{maximum:100})).rejects.toThrow('size limit');}finally{await s.close();}});
it('cancels a running request and enforces a wall-clock deadline',async()=>{const s=await server(()=>{});try{await expect(p.requestJSON(s.url,{timeout:30})).rejects.toThrow('timed out');const controller=new AbortController(),pending=p.requestJSON(s.url,{signal:controller.signal});controller.abort();await expect(pending).rejects.toThrow('cancelled');}finally{await s.close();}});
it('writes credentials only through encryption and preserves corrupt saved data',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'ai-vault-'));try{const file=path.join(dir,'credentials.encrypted'),storage={isEncryptionAvailable:()=>true,encryptString:(s:string)=>Buffer.from(s).map(x=>x^85),decryptString:(b:Buffer)=>Buffer.from(b).map(x=>x^85).toString()};const v=new Vault(file,storage);await v.write({token:'synthetic-secret'});expect((await fs.readFile(file,'utf8'))).not.toContain('synthetic-secret');expect(await v.read()).toEqual({token:'synthetic-secret'});storage.isEncryptionAvailable=()=>false;await expect(v.write({token:'replacement'})).rejects.toThrow('not saved');storage.isEncryptionAvailable=()=>true;expect(await v.read()).toEqual({token:'synthetic-secret'});await fs.writeFile(file,'corrupt');await expect(v.read()).rejects.toThrow('preserved');expect(await fs.readFile(file,'utf8')).toBe('corrupt');}finally{const resolved=path.resolve(dir);if(!resolved.startsWith(path.resolve(os.tmpdir())+path.sep))throw Error('Invalid cleanup root');await fs.rm(resolved,{recursive:true,force:true});}});
