const {app,BrowserWindow,Menu,protocol,net,session,ipcMain,dialog,safeStorage}=require('electron');
const fs=require('node:fs/promises'),path=require('node:path'),{pathToFileURL}=require('node:url'),{randomUUID}=require('node:crypto');
const {Vault,atomic}=require('./vault.cjs'),provider=require('./provider.cjs');
const projects=require('../content/projects.json');
app.setName('AI Engineering');app.setAppUserModelId('com.lukemclaughlin.aiengineering.windows');
protocol.registerSchemesAsPrivileged([{scheme:'app',privileges:{standard:true,secure:true,supportFetchAPI:true,corsEnabled:true}}]);
let win,vault,connection=null,controller=null,connecting=false;
const origin='app://ai-engineering/';
function trusted(e){if(!win||e.sender!==win.webContents||e.senderFrame!==win.webContents.mainFrame||!e.senderFrame.url.startsWith(origin))throw Error('Untrusted request.');}
function handle(name,fn){ipcMain.handle(name,(e,...args)=>{trusted(e);return fn(...args);});}
async function confirm(config){const response=await dialog.showMessageBox(win,{type:'question',title:'Enable optional tutor connection?',message:'Send tutor questions to '+provider.PRESETS[config.provider][0]+'?',detail:'Destination: '+config.endpoint+'\nModel: '+config.model+'\n\nOnly tutor questions, recent tutor conversation and relevant bundled course material are sent. Provider charges may apply. This permission lasts until you close the app or disconnect. Offline Core remains available.',buttons:['Cancel','Enable for this session'],defaultId:0,cancelId:0,noLink:true});return response.response===1;}
async function status(){const saved=await vault.read();return {presets:provider.PRESETS,saved:saved?.config||null,credentialStored:!!saved?.token,enabled:!!connection,encryptionAvailable:safeStorage.isEncryptionAvailable()};}
if(!app.requestSingleInstanceLock())app.quit();
else app.whenReady().then(async()=>{
 vault=new Vault(path.join(app.getPath('userData'),'tutor-connection.encrypted'),safeStorage);
 const root=path.resolve(app.getAppPath(),'dist');
 protocol.handle('app',request=>{try{const u=new URL(request.url),file=path.resolve(root,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(u.hostname!=='ai-engineering'||!file.startsWith(root+path.sep))return new Response('Not found',{status:404});return net.fetch(pathToFileURL(file).href);}catch{return new Response('Invalid path',{status:400});}});
 session.defaultSession.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*','ws://*/*','wss://*/*']},(_d,callback)=>callback({cancel:true}));
 session.defaultSession.setPermissionRequestHandler((_w,_p,callback)=>callback(false));session.defaultSession.setPermissionCheckHandler(()=>false);
 handle('tutor:status',status);
 handle('tutor:connect',async raw=>{if(connecting)throw Error('A connection decision is already open.');connecting=true;try{const config=provider.validateConfig(raw),token=String(raw.token||'').trim();if(token.length>16384||/[\r\n\x00]/.test(token)||(!provider.isLocal(config.provider)&&!token))throw Error('Enter a valid API key.');if(!await confirm(config))return false;await vault.write({config,token});controller?.abort();connection={config,token};return true;}finally{connecting=false;}});
 handle('tutor:enable',async()=>{if(connecting)throw Error('A connection decision is already open.');connecting=true;try{const saved=await vault.read();if(!saved?.config)throw Error('Save a connection first.');provider.validateConfig(saved.config);if(!await confirm(saved.config))return false;controller?.abort();connection=saved;return true;}finally{connecting=false;}});
 handle('tutor:disconnect',()=>{controller?.abort();connection=null;return true;});
 handle('tutor:forget',async()=>{controller?.abort();connection=null;await vault.write(null);return true;});
 handle('tutor:ask',async payload=>{if(!connection)throw Error('Enable a provider for this session first.');if(controller)throw Error('A tutor request is already running.');const active=connection;controller=new AbortController();try{return await provider.answer(active.config,active.token,payload,controller.signal);}finally{controller=null;}});
 handle('tutor:cancel',()=>{controller?.abort();return true;});handle('tutor:discover',provider.discover);
 handle('data:export',async text=>{if(typeof text!=='string'||Buffer.byteLength(text)>8_000_000)throw Error('Backup exceeds 8 MB.');const parsed=JSON.parse(text);if(parsed?.version!==1)throw Error('Invalid backup.');const result=await dialog.showSaveDialog(win,{title:'Export AI Engineering progress and workspaces',defaultPath:'AI-Engineering-backup-'+new Date().toISOString().slice(0,10)+'.json',filters:[{name:'Progress backup',extensions:['json']}]});if(result.canceled||!result.filePath)return false;await atomic(result.filePath,text);return true;});
 handle('data:import',async()=>{const result=await dialog.showOpenDialog(win,{title:'Import AI Engineering backup',properties:['openFile'],filters:[{name:'Progress backup',extensions:['json']}]});if(result.canceled||!result.filePaths[0])return null;const file=result.filePaths[0],stat=await fs.stat(file);if(!stat.isFile()||stat.size>8_000_000)throw Error('Choose a backup under 8 MB.');return fs.readFile(file,'utf8');});
 handle('project:export',async data=>{const project=projects.find(p=>p.id===data?.id);if(!project||!data.files||typeof data.files!=='object')throw Error('Unknown project.');const files=project.starterFiles.map(f=>{const text=data.files[f.name];if(typeof text!=='string'||Buffer.byteLength(text)>400000||!/^[-a-zA-Z0-9_. ]+$/.test(f.name)||/^\.|[. ]$/.test(f.name)||/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(f.name))throw Error('Invalid project file.');return {name:f.name,text};});const result=await dialog.showOpenDialog(win,{title:'Choose a parent folder for a new project copy',properties:['openDirectory']});if(result.canceled||!result.filePaths[0])return false;const parent=await fs.realpath(result.filePaths[0]),destination=path.join(parent,project.id+'-'+randomUUID().slice(0,8));await fs.mkdir(destination);for(const f of files)await fs.writeFile(path.join(destination,f.name),f.text,{encoding:'utf8',flag:'wx'});return destination;});
 Menu.setApplicationMenu(Menu.buildFromTemplate([{label:'File',submenu:[{role:'quit'}]},{label:'Edit',submenu:[{role:'undo'},{role:'redo'},{type:'separator'},{role:'cut'},{role:'copy'},{role:'paste'},{role:'selectAll'}]},{label:'View',submenu:[{role:'resetZoom'},{role:'zoomIn'},{role:'zoomOut'},{role:'togglefullscreen'}]}]));
 win=new BrowserWindow({width:1280,height:900,minWidth:880,minHeight:650,show:false,title:'AI Engineering',backgroundColor:'#0b1020',icon:path.join(app.getAppPath(),'resources/AppIcon-1024.png'),webPreferences:{preload:path.join(__dirname,'preload.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false}});
 win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',(event,url)=>{if(!url.startsWith(origin))event.preventDefault();});win.webContents.on('will-attach-webview',event=>event.preventDefault());win.once('ready-to-show',()=>win.show());await win.loadURL(origin);
});
app.on('second-instance',()=>{if(win?.isMinimized())win.restore();win?.focus();});app.on('before-quit',()=>controller?.abort());app.on('window-all-closed',()=>app.quit());
